### PR TITLE
Override use of default socket_map in asyncore.  

### PR DESCRIPTION
**Pull request by jpmec**
This allows Servers to be nested.  
Also, run_client will now wait for server instead of exiting with exception if server is not already started.

### CODE REVIEW

**Comment by michaelfairley** [comment]
I just pushed 0b1953209f15316f3e7d33bf83d03cb8b7a6d1a1, which includes the socket map changes. Thanks for pointing out that that needed to happen and providing your code.

I'm inclined to not accept the client polling changes. I want to keep mincemeat.py small, and I'd rather leave orchestration/restarting/etc to be handled outside of mmp (e.g. in a wrapper shell script).

Thanks again!

**Comment by jpmec** [comment]
Hi Michael, no problem.  One thing, do you mind including the README changes that show how to nest MapReduce?  This was the main problem I was trying to solve that caused me to dig into the code.

**Comment by jpmec** [comment]
Hi Michael, one more thing on the client polling changes.  I understand your concern.  How would you like to see this done?  Personally, I don't like shell scripts and I like to stay with a single language for the toolchain (when possible).  For instance, if I am writing a map reduce program in Python, I would like to use Python for configuration and and management.

I was hoping you would have some time to discuss this, because I have some ideas for some Python code to make this happen.

**Comment by michaelfairley** [comment]
Re nesting: I'm fairly certain that chaining (i.e. taking the output of one MR job and using it as the input to the next) and nesting (i.e. starting and MR job from within another one) can accomplish the same set of things, but that chaining is generally simper to think about and is easier operationally, so I'm not inclined to encourage nesting.

Re orchestration: Totally valid. It's also possible to script the starting of mincemeat clients from Python, letting you more or less take the polling code you wrote and use it outside of mincemeat. I added a brief example to the readme showing how to use the clients from within Python, so I hope that helps.

Let me know if you have any other questions or suggestions for mincemeat. These have been helpful!

**Comment by jpmec** [comment]
Hi Michael,

I am still new to MR in general, so I don't completely understand chaining versus nesting as you have described it.  Are you saying that with chaining I would need to write the output of one job to disk?

Here is the use case I have encountered:

Assume simple word counting example using a distributed file system (each client can access the data)

If you have the case of many small files then you can setup your MR so that the server will send file names to clients and each client will process a single file.  This works well without chaining or nesting.

If you have the case of one large file then you can setup your MR so that the server will send chunks to the clients (in the degenerate case, it just sends single lines), and each client will process a single line (or set of lines).  This works well without chaining or nesting.

However, if you have many files, some small and some very large, then you cannot optimize the solution.  What I used was a solution where the first layer server sent file names to first layer clients (first layer clients are also second layer servers).  The second layer servers could then send out the chunks to second layer clients.

You can then create a pool of first layer clients and a pool of second layer clients to service the job.  No matter what the file layout (lots of small files, single large file, or a mix), this will work and scale with less programmer intervention.

Does this make sense?

If you still disagree (BTW, I respect that if you do, I'm not trying to be argumentative.  I'm trying to learn MR with a dead-easy library), you might want to display an example of how you would recommend users to use mincemeat to solve the issues I have outlined above.

---

About orchestration, I will try to throw together a simple python file that makes this easy for the end user.  Would you like me to add this to the mincemeat project, or would you rather see this as a different repo?

**Comment by michaelfairley** [comment]
Here's roughly what the chained version of that problem could look like. Basically, the first job does nothing but split the files, and the second one is just the normal word count task.

``` python
s1 = mincemeat.Server()
s1.datasource = filenames
s1.mapfn = split_the_files_into_chunks
s1.reduce = identity
chunks = s1.run_server(password="server1")

s2 = mincemeat.Server()
s2.datasource = chunks
s2.mapfn = count_words
s2.reducefn = combine_counts
counts = s2.run_server(password="server2")
```

There's a couple things about this solution that I think are a bit simpler than nesting:
- You don't need a second layer of clients that have to connect to a different set of servers than the first layer clients.
- The map and reduce functions remain simple and agnostic as to how they're being composed.
- You can snapshot the data to disk in between the phases (maybe not useful for this task, but could be if the first phase is lengthy).

(I'm also not super convinced this optimization is necessary for this problem in practice. Sending the chunks across the network is probably going to be more expensive than just doing the counting on the machine where you're reading the large file.)

This has been a fun discussion! I haven't actually thought that much about MR in a while, and I'd never seen the idea of nesting MR jobs before.

---

Having a repo with some orchestration recipes in it would be very cool, and I'd be more than happy to link to it from the main mincemeat repo.

**Comment by jpmec** [comment]
Hi Michael,

I've put together a simple mincemeat client runner here:

https://github.com/jpmec/shepherdpy

I'll be adding some more examples to the documentation soon.  If you want to link to your project, I think it might be useful for other mincemeat.py users.  Thanks!

**Comment by michaelfairley** [comment]
Very cool! I added to note the mincemeat's readme.

**Pull request closed without merging**
